baseURL = "http://www.example.com"
title = "Meggie Ladlow"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "creative development"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "MunifTanjim"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
hideMainMenu = false
showReadingTime = true

[params.sidebar]
enable = true

[params.widgets]
sidebar = ["about"]

#[params.opengraph.facebook]
#admins = [] # array of Facebook IDs
#appID = ""
#pageID = ""

#[params.opengraph.twitter]
#page = "meggiel" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "MunifTanjim"
email = "meggiel@pm.me"
#facebook = "MunifTanjim"
github = "mladlow"
#instagram = "MunifTanjim"
linkedin = "mladlow"
twitter = "meggiel"

[params.social.config]
platforms = ["github","twitter","email","linkedin"]

[params.comments]
enable = false

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
weight = 0
identifier = "home"
url = "/"

[[menu.main]]
name = "About"
weight = 1
identifier ="about me"
url = "/about/"

[[menu.main]]
name = "Repo"
weight = 2
identifier = "repository"
url = "https://github.com/mladlow"

[[menu.main]]
name = "MD Farms"
weight = 3
identifier = "md horse farms"
url = "https://meggiel.com/maryland-farms/index.html"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
